apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "b-5.rgumiero.16f8b1.c25.kafka.us-east-1.amazonaws.com:9092,b-1.rgumiero.16f8b1.c25.kafka.us-east-1.amazonaws.com:9092,b-2.rgumiero.16f8b1.c25.kafka.us-east-1.amazonaws.com:9092"
        topics => "log-messages"
        group_id => "logstash"
        client_id => "logstash1"
        codec => "json"
      }
    }
    output {
      opensearch {
        hosts  => ["${AOS_HOSTS}"]
        auth_type => {
          type => 'basic'
          user => "${AOS_USER}"
          password => "$AOS_PASSWORD}"
        }
        index => "log-messages-%{+YYYY.MM.dd}"
      }
    }
