apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: logstash-opensearch
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "${MSK_BOOTSTRAP_SERVERS}"
        topics => "${MSK_TOPICS}"
        group_id => "${MSK_CONSUMER_GRP_ID}"
        client_id => "${MSK_CONSUMER_CLI_ID}"
        codec => "json"
        
      }
    }
    output {
      opensearch {
        hosts  => ["${AOS_HOSTS}"]
        auth_type => {
          type => 'basic'
          user => "${AOS_USER}"
          password => "$AOS_PASSWORD}"
        }
        index => "${AOS_INDEX}-%{+YYYY.MM.dd}"
      }
    }
