---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: logstash-opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
        name: logstash
        ports:
        - containerPort: 25826
        - containerPort: 5044
        resources: # Verify the amount of requests
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        env:
        - name: AOS_HOSTS
          value: "https://vpc-sample.us-east-1.es.amazonaws.com:443"
        - name: AOS_USER
          value: "username"
        - name: AOS_PASSWORD
          value: "p@ssword"
        - name: AOS_INDEX
          value: "log-messages"
        - name: MSK_BOOTSTRAP_SERVERS
          value: "b-1.sample.kafka.us-east-1.amazonaws.com:9092,b-2.sample.kafka.us-east-1.amazonaws.com:9092,b-3.sample.kafka.us-east-1.amazonaws.com:9092"
        - name: MSK_TOPICS
          value: "log-messages"
        - name: MSK_CONSUMER_GRP_ID
          value: "logstash-grp"
         - name: MSK_CONSUMER_CLI_ID
          value: "logstash-cli-01"
      volumes:
      - name: config-volume
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.conf
              path: logstash.conf
