apiVersion: v1
kind: Pod
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: logstash-opensearch
spec:
  containers:
  - image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    name: logstash
    ports:
    - containerPort: 25826
    - containerPort: 5044
    env:
    - name: AOS_HOSTS
      value: "https://vpc-rgumiero-opensearch-vpc-okta-iraucwcpipvlnh4c6oca7fjjp4.us-east-1.es.amazonaws.com:443"
    - name: AOS_USER
      value: "opensearch"
    - name: AOS_PASSWORD
      value: "opensearch"
    - name: MSK_BOOTSRAP_SERVERS
      value: "b-5.rgumiero.16f8b1.c25.kafka.us-east-1.amazonaws.com:9092,b-1.rgumiero.16f8b1.c25.kafka.us-east-1.amazonaws.com:9092,b-2.rgumiero.16f8b1.c25.kafka.us-east-1.amazonaws.com:9092"
    resources: {}
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/logstash/config
    - name: logstash-pipeline-volume
      mountPath: /usr/share/logstash/pipeline
  restartPolicy: OnFailure
  volumes:
  - name: config-volume
    configMap:
      name: logstash-configmap
      items:
        - key: logstash.yml
          path: logstash.yml
  - name: logstash-pipeline-volume
    configMap:
      name: logstash-configmap
      items:
        - key: logstash.conf
          path: logstash.conf

status: {}
